---
application:
  name: "proyect-mapa-de-karnought"
  project: "karnaought-umg"
  organization: "QoveryCommunity"
  port: 3000
routers:
- name: "main-proyect-mapa-de-karnought"
  routes:
  - application_name: "proyect-mapa-de-karnought"
    paths:
    - "/*"
